name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run start:test & npx wait-on http://localhost:3000
      - uses: cypress-io/github-action@v2
        with:
          start: npm run start:server
          wait-on: 'http://localhost:5000'
